/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingListRouteImport } from './routes/waiting-list'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StaffDevRouteImport } from './routes/staff-dev'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SendRouteImport } from './routes/send'
import { Route as RotaRouteImport } from './routes/rota'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RevenueReportRouteImport } from './routes/revenue-report'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RelativesRouteImport } from './routes/relatives'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as OfstedRouteImport } from './routes/ofsted'
import { Route as NewsfeedRouteImport } from './routes/newsfeed'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as FundedHoursRouteImport } from './routes/funded-hours'
import { Route as FireRegisterRouteImport } from './routes/fire-register'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyLogsRouteImport } from './routes/daily-logs'
import { Route as ConsentsRouteImport } from './routes/consents'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookingRequestsRouteImport } from './routes/booking-requests'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AccidentBookRouteImport } from './routes/accident-book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceIndexRouteImport } from './routes/compliance/index'
import { Route as ChildrenIndexRouteImport } from './routes/children/index'
import { Route as ComplianceTrainingRouteImport } from './routes/compliance/training'
import { Route as ComplianceRiskAssessmentsRouteImport } from './routes/compliance/risk-assessments'
import { Route as CompliancePoliciesRouteImport } from './routes/compliance/policies'
import { Route as ChildrenChildIdRouteImport } from './routes/children/$childId'

const WaitingListRoute = WaitingListRouteImport.update({
  id: '/waiting-list',
  path: '/waiting-list',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDevRoute = StaffDevRouteImport.update({
  id: '/staff-dev',
  path: '/staff-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaRoute = RotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueReportRoute = RevenueReportRouteImport.update({
  id: '/revenue-report',
  path: '/revenue-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RelativesRoute = RelativesRouteImport.update({
  id: '/relatives',
  path: '/relatives',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const OfstedRoute = OfstedRouteImport.update({
  id: '/ofsted',
  path: '/ofsted',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsfeedRoute = NewsfeedRouteImport.update({
  id: '/newsfeed',
  path: '/newsfeed',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const FundedHoursRoute = FundedHoursRouteImport.update({
  id: '/funded-hours',
  path: '/funded-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const FireRegisterRoute = FireRegisterRouteImport.update({
  id: '/fire-register',
  path: '/fire-register',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyLogsRoute = DailyLogsRouteImport.update({
  id: '/daily-logs',
  path: '/daily-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentsRoute = ConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRequestsRoute = BookingRequestsRouteImport.update({
  id: '/booking-requests',
  path: '/booking-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentBookRoute = AccidentBookRouteImport.update({
  id: '/accident-book',
  path: '/accident-book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIndexRoute = ChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceTrainingRoute = ComplianceTrainingRouteImport.update({
  id: '/compliance/training',
  path: '/compliance/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRiskAssessmentsRoute =
  ComplianceRiskAssessmentsRouteImport.update({
    id: '/compliance/risk-assessments',
    path: '/compliance/risk-assessments',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompliancePoliciesRoute = CompliancePoliciesRouteImport.update({
  id: '/compliance/policies',
  path: '/compliance/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenChildIdRoute = ChildrenChildIdRouteImport.update({
  id: '/children/$childId',
  path: '/children/$childId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accident-book': typeof AccidentBookRoute
  '/assessment': typeof AssessmentRoute
  '/billing': typeof BillingRoute
  '/booking-requests': typeof BookingRequestsRoute
  '/calendar': typeof CalendarRoute
  '/consents': typeof ConsentsRoute
  '/daily-logs': typeof DailyLogsRoute
  '/dashboard': typeof DashboardRoute
  '/enquiries': typeof EnquiriesRoute
  '/finance': typeof FinanceRoute
  '/fire-register': typeof FireRegisterRoute
  '/funded-hours': typeof FundedHoursRoute
  '/funding': typeof FundingRoute
  '/gdpr': typeof GdprRoute
  '/incidents': typeof IncidentsRoute
  '/invoices': typeof InvoicesRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/messages': typeof MessagesRoute
  '/mfa': typeof MfaRoute
  '/monitoring': typeof MonitoringRoute
  '/newsfeed': typeof NewsfeedRoute
  '/ofsted': typeof OfstedRoute
  '/planning': typeof PlanningRoute
  '/reflections': typeof ReflectionsRoute
  '/register': typeof RegisterRoute
  '/relatives': typeof RelativesRoute
  '/reports': typeof ReportsRoute
  '/revenue-report': typeof RevenueReportRoute
  '/rooms': typeof RoomsRoute
  '/rota': typeof RotaRoute
  '/send': typeof SendRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-dev': typeof StaffDevRoute
  '/users': typeof UsersRoute
  '/waiting-list': typeof WaitingListRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/compliance/policies': typeof CompliancePoliciesRoute
  '/compliance/risk-assessments': typeof ComplianceRiskAssessmentsRoute
  '/compliance/training': typeof ComplianceTrainingRoute
  '/children/': typeof ChildrenIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accident-book': typeof AccidentBookRoute
  '/assessment': typeof AssessmentRoute
  '/billing': typeof BillingRoute
  '/booking-requests': typeof BookingRequestsRoute
  '/calendar': typeof CalendarRoute
  '/consents': typeof ConsentsRoute
  '/daily-logs': typeof DailyLogsRoute
  '/dashboard': typeof DashboardRoute
  '/enquiries': typeof EnquiriesRoute
  '/finance': typeof FinanceRoute
  '/fire-register': typeof FireRegisterRoute
  '/funded-hours': typeof FundedHoursRoute
  '/funding': typeof FundingRoute
  '/gdpr': typeof GdprRoute
  '/incidents': typeof IncidentsRoute
  '/invoices': typeof InvoicesRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/messages': typeof MessagesRoute
  '/mfa': typeof MfaRoute
  '/monitoring': typeof MonitoringRoute
  '/newsfeed': typeof NewsfeedRoute
  '/ofsted': typeof OfstedRoute
  '/planning': typeof PlanningRoute
  '/reflections': typeof ReflectionsRoute
  '/register': typeof RegisterRoute
  '/relatives': typeof RelativesRoute
  '/reports': typeof ReportsRoute
  '/revenue-report': typeof RevenueReportRoute
  '/rooms': typeof RoomsRoute
  '/rota': typeof RotaRoute
  '/send': typeof SendRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-dev': typeof StaffDevRoute
  '/users': typeof UsersRoute
  '/waiting-list': typeof WaitingListRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/compliance/policies': typeof CompliancePoliciesRoute
  '/compliance/risk-assessments': typeof ComplianceRiskAssessmentsRoute
  '/compliance/training': typeof ComplianceTrainingRoute
  '/children': typeof ChildrenIndexRoute
  '/compliance': typeof ComplianceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accident-book': typeof AccidentBookRoute
  '/assessment': typeof AssessmentRoute
  '/billing': typeof BillingRoute
  '/booking-requests': typeof BookingRequestsRoute
  '/calendar': typeof CalendarRoute
  '/consents': typeof ConsentsRoute
  '/daily-logs': typeof DailyLogsRoute
  '/dashboard': typeof DashboardRoute
  '/enquiries': typeof EnquiriesRoute
  '/finance': typeof FinanceRoute
  '/fire-register': typeof FireRegisterRoute
  '/funded-hours': typeof FundedHoursRoute
  '/funding': typeof FundingRoute
  '/gdpr': typeof GdprRoute
  '/incidents': typeof IncidentsRoute
  '/invoices': typeof InvoicesRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/messages': typeof MessagesRoute
  '/mfa': typeof MfaRoute
  '/monitoring': typeof MonitoringRoute
  '/newsfeed': typeof NewsfeedRoute
  '/ofsted': typeof OfstedRoute
  '/planning': typeof PlanningRoute
  '/reflections': typeof ReflectionsRoute
  '/register': typeof RegisterRoute
  '/relatives': typeof RelativesRoute
  '/reports': typeof ReportsRoute
  '/revenue-report': typeof RevenueReportRoute
  '/rooms': typeof RoomsRoute
  '/rota': typeof RotaRoute
  '/send': typeof SendRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-dev': typeof StaffDevRoute
  '/users': typeof UsersRoute
  '/waiting-list': typeof WaitingListRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/compliance/policies': typeof CompliancePoliciesRoute
  '/compliance/risk-assessments': typeof ComplianceRiskAssessmentsRoute
  '/compliance/training': typeof ComplianceTrainingRoute
  '/children/': typeof ChildrenIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accident-book'
    | '/assessment'
    | '/billing'
    | '/booking-requests'
    | '/calendar'
    | '/consents'
    | '/daily-logs'
    | '/dashboard'
    | '/enquiries'
    | '/finance'
    | '/fire-register'
    | '/funded-hours'
    | '/funding'
    | '/gdpr'
    | '/incidents'
    | '/invoices'
    | '/journal'
    | '/login'
    | '/medications'
    | '/messages'
    | '/mfa'
    | '/monitoring'
    | '/newsfeed'
    | '/ofsted'
    | '/planning'
    | '/reflections'
    | '/register'
    | '/relatives'
    | '/reports'
    | '/revenue-report'
    | '/rooms'
    | '/rota'
    | '/send'
    | '/sessions'
    | '/settings'
    | '/staff'
    | '/staff-dev'
    | '/users'
    | '/waiting-list'
    | '/children/$childId'
    | '/compliance/policies'
    | '/compliance/risk-assessments'
    | '/compliance/training'
    | '/children/'
    | '/compliance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accident-book'
    | '/assessment'
    | '/billing'
    | '/booking-requests'
    | '/calendar'
    | '/consents'
    | '/daily-logs'
    | '/dashboard'
    | '/enquiries'
    | '/finance'
    | '/fire-register'
    | '/funded-hours'
    | '/funding'
    | '/gdpr'
    | '/incidents'
    | '/invoices'
    | '/journal'
    | '/login'
    | '/medications'
    | '/messages'
    | '/mfa'
    | '/monitoring'
    | '/newsfeed'
    | '/ofsted'
    | '/planning'
    | '/reflections'
    | '/register'
    | '/relatives'
    | '/reports'
    | '/revenue-report'
    | '/rooms'
    | '/rota'
    | '/send'
    | '/sessions'
    | '/settings'
    | '/staff'
    | '/staff-dev'
    | '/users'
    | '/waiting-list'
    | '/children/$childId'
    | '/compliance/policies'
    | '/compliance/risk-assessments'
    | '/compliance/training'
    | '/children'
    | '/compliance'
  id:
    | '__root__'
    | '/'
    | '/accident-book'
    | '/assessment'
    | '/billing'
    | '/booking-requests'
    | '/calendar'
    | '/consents'
    | '/daily-logs'
    | '/dashboard'
    | '/enquiries'
    | '/finance'
    | '/fire-register'
    | '/funded-hours'
    | '/funding'
    | '/gdpr'
    | '/incidents'
    | '/invoices'
    | '/journal'
    | '/login'
    | '/medications'
    | '/messages'
    | '/mfa'
    | '/monitoring'
    | '/newsfeed'
    | '/ofsted'
    | '/planning'
    | '/reflections'
    | '/register'
    | '/relatives'
    | '/reports'
    | '/revenue-report'
    | '/rooms'
    | '/rota'
    | '/send'
    | '/sessions'
    | '/settings'
    | '/staff'
    | '/staff-dev'
    | '/users'
    | '/waiting-list'
    | '/children/$childId'
    | '/compliance/policies'
    | '/compliance/risk-assessments'
    | '/compliance/training'
    | '/children/'
    | '/compliance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccidentBookRoute: typeof AccidentBookRoute
  AssessmentRoute: typeof AssessmentRoute
  BillingRoute: typeof BillingRoute
  BookingRequestsRoute: typeof BookingRequestsRoute
  CalendarRoute: typeof CalendarRoute
  ConsentsRoute: typeof ConsentsRoute
  DailyLogsRoute: typeof DailyLogsRoute
  DashboardRoute: typeof DashboardRoute
  EnquiriesRoute: typeof EnquiriesRoute
  FinanceRoute: typeof FinanceRoute
  FireRegisterRoute: typeof FireRegisterRoute
  FundedHoursRoute: typeof FundedHoursRoute
  FundingRoute: typeof FundingRoute
  GdprRoute: typeof GdprRoute
  IncidentsRoute: typeof IncidentsRoute
  InvoicesRoute: typeof InvoicesRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  MedicationsRoute: typeof MedicationsRoute
  MessagesRoute: typeof MessagesRoute
  MfaRoute: typeof MfaRoute
  MonitoringRoute: typeof MonitoringRoute
  NewsfeedRoute: typeof NewsfeedRoute
  OfstedRoute: typeof OfstedRoute
  PlanningRoute: typeof PlanningRoute
  ReflectionsRoute: typeof ReflectionsRoute
  RegisterRoute: typeof RegisterRoute
  RelativesRoute: typeof RelativesRoute
  ReportsRoute: typeof ReportsRoute
  RevenueReportRoute: typeof RevenueReportRoute
  RoomsRoute: typeof RoomsRoute
  RotaRoute: typeof RotaRoute
  SendRoute: typeof SendRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StaffDevRoute: typeof StaffDevRoute
  UsersRoute: typeof UsersRoute
  WaitingListRoute: typeof WaitingListRoute
  ChildrenChildIdRoute: typeof ChildrenChildIdRoute
  CompliancePoliciesRoute: typeof CompliancePoliciesRoute
  ComplianceRiskAssessmentsRoute: typeof ComplianceRiskAssessmentsRoute
  ComplianceTrainingRoute: typeof ComplianceTrainingRoute
  ChildrenIndexRoute: typeof ChildrenIndexRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-list': {
      id: '/waiting-list'
      path: '/waiting-list'
      fullPath: '/waiting-list'
      preLoaderRoute: typeof WaitingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-dev': {
      id: '/staff-dev'
      path: '/staff-dev'
      fullPath: '/staff-dev'
      preLoaderRoute: typeof StaffDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota': {
      id: '/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof RotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-report': {
      id: '/revenue-report'
      path: '/revenue-report'
      fullPath: '/revenue-report'
      preLoaderRoute: typeof RevenueReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatives': {
      id: '/relatives'
      path: '/relatives'
      fullPath: '/relatives'
      preLoaderRoute: typeof RelativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofsted': {
      id: '/ofsted'
      path: '/ofsted'
      fullPath: '/ofsted'
      preLoaderRoute: typeof OfstedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsfeed': {
      id: '/newsfeed'
      path: '/newsfeed'
      fullPath: '/newsfeed'
      preLoaderRoute: typeof NewsfeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funded-hours': {
      id: '/funded-hours'
      path: '/funded-hours'
      fullPath: '/funded-hours'
      preLoaderRoute: typeof FundedHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fire-register': {
      id: '/fire-register'
      path: '/fire-register'
      fullPath: '/fire-register'
      preLoaderRoute: typeof FireRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-logs': {
      id: '/daily-logs'
      path: '/daily-logs'
      fullPath: '/daily-logs'
      preLoaderRoute: typeof DailyLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consents': {
      id: '/consents'
      path: '/consents'
      fullPath: '/consents'
      preLoaderRoute: typeof ConsentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-requests': {
      id: '/booking-requests'
      path: '/booking-requests'
      fullPath: '/booking-requests'
      preLoaderRoute: typeof BookingRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accident-book': {
      id: '/accident-book'
      path: '/accident-book'
      fullPath: '/accident-book'
      preLoaderRoute: typeof AccidentBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/': {
      id: '/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof ChildrenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/training': {
      id: '/compliance/training'
      path: '/compliance/training'
      fullPath: '/compliance/training'
      preLoaderRoute: typeof ComplianceTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/risk-assessments': {
      id: '/compliance/risk-assessments'
      path: '/compliance/risk-assessments'
      fullPath: '/compliance/risk-assessments'
      preLoaderRoute: typeof ComplianceRiskAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/policies': {
      id: '/compliance/policies'
      path: '/compliance/policies'
      fullPath: '/compliance/policies'
      preLoaderRoute: typeof CompliancePoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$childId': {
      id: '/children/$childId'
      path: '/children/$childId'
      fullPath: '/children/$childId'
      preLoaderRoute: typeof ChildrenChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccidentBookRoute: AccidentBookRoute,
  AssessmentRoute: AssessmentRoute,
  BillingRoute: BillingRoute,
  BookingRequestsRoute: BookingRequestsRoute,
  CalendarRoute: CalendarRoute,
  ConsentsRoute: ConsentsRoute,
  DailyLogsRoute: DailyLogsRoute,
  DashboardRoute: DashboardRoute,
  EnquiriesRoute: EnquiriesRoute,
  FinanceRoute: FinanceRoute,
  FireRegisterRoute: FireRegisterRoute,
  FundedHoursRoute: FundedHoursRoute,
  FundingRoute: FundingRoute,
  GdprRoute: GdprRoute,
  IncidentsRoute: IncidentsRoute,
  InvoicesRoute: InvoicesRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  MedicationsRoute: MedicationsRoute,
  MessagesRoute: MessagesRoute,
  MfaRoute: MfaRoute,
  MonitoringRoute: MonitoringRoute,
  NewsfeedRoute: NewsfeedRoute,
  OfstedRoute: OfstedRoute,
  PlanningRoute: PlanningRoute,
  ReflectionsRoute: ReflectionsRoute,
  RegisterRoute: RegisterRoute,
  RelativesRoute: RelativesRoute,
  ReportsRoute: ReportsRoute,
  RevenueReportRoute: RevenueReportRoute,
  RoomsRoute: RoomsRoute,
  RotaRoute: RotaRoute,
  SendRoute: SendRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StaffDevRoute: StaffDevRoute,
  UsersRoute: UsersRoute,
  WaitingListRoute: WaitingListRoute,
  ChildrenChildIdRoute: ChildrenChildIdRoute,
  CompliancePoliciesRoute: CompliancePoliciesRoute,
  ComplianceRiskAssessmentsRoute: ComplianceRiskAssessmentsRoute,
  ComplianceTrainingRoute: ComplianceTrainingRoute,
  ChildrenIndexRoute: ChildrenIndexRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
