import { createRouter } from '@tanstack/react-router';
// Generated by @tanstack/router-plugin from src/routes on dev/build.
import { routeTree } from './routeTree.gen';

export const router = createRouter({ routeTree });

// Type-safe navigation across the app.
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
